"""Added student_data table

Revision ID: 28f5815eecbf
Revises: 7ee34fb88cca
Create Date: 2025-03-29 12:41:27.436654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f5815eecbf'
down_revision: Union[str, None] = '7ee34fb88cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('course1', sa.Numeric(), nullable=False),
    sa.Column('course2', sa.Numeric(), nullable=True),
    sa.Column('course3', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trade_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scrip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tradetype', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entryprice', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('stoploss', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('target1', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('target2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('target3', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exchangeid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trade_history_pkey')
    )
    op.drop_table('student_data')
    # ### end Alembic commands ###
