"""Initial migration

Revision ID: 7ee34fb88cca
Revises: 
Create Date: 2025-03-29 12:31:34.981051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee34fb88cca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrip', sa.String(), nullable=False),
    sa.Column('tradetype', sa.String(), nullable=False),
    sa.Column('entryprice', sa.Numeric(), nullable=False),
    sa.Column('stoploss', sa.Numeric(), nullable=False),
    sa.Column('target1', sa.Numeric(), nullable=False),
    sa.Column('target2', sa.Numeric(), nullable=True),
    sa.Column('target3', sa.Numeric(), nullable=True),
    sa.Column('exchangeid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_history')
    # ### end Alembic commands ###
